name: Deploy Static Website
on:
  push:
    branches:
      - production # Đảm bảo chỉ chạy khi Backend đẩy code vào nhánh production

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Bỏ qua hoàn toàn bước Setup Node.js và npm install

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          # Thay 'dist' thành '.' để deploy toàn bộ thư mục hiện tại
          command: pages deploy . --project-name=teicloud-demo